import os
import json
import uuid
import math
import string
import re
import secrets
from functools import wraps
from datetime import datetime, timezone
from collections import Counter
from pathlib import Path

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Groq client
# ---------------------------------------------------------------------------
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ---------------------------------------------------------------------------
# Local storage
# ---------------------------------------------------------------------------
DATA_DIR = Path(os.environ.get("PROVENANCE_DATA_DIR", ".data"))
LOG_FILE = DATA_DIR / "audit_log.json"
CONTENT_FILE = DATA_DIR / "content_store.json"
CERT_FILE = DATA_DIR / "certificate_store.json"


def _read_json(path, default):
    path = Path(path)
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return default


def _write_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n")


def read_log():
    return _read_json(LOG_FILE, [])


def write_log(entries):
    _write_json(LOG_FILE, entries)


def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


def read_store():
    return _read_json(CONTENT_FILE, {})


def write_store(store):
    _write_json(CONTENT_FILE, store)


def store_content(content_id, data):
    store = read_store()
    store[content_id] = data
    write_store(store)


def get_content(content_id):
    return read_store().get(content_id)


def update_content_status(content_id, status):
    store = read_store()
    if content_id in store:
        store[content_id]["status"] = status
        write_store(store)
        return True
    return False


def read_certs():
    return _read_json(CERT_FILE, {})


def write_certs(certs):
    _write_json(CERT_FILE, certs)


def is_verified(creator_id: str) -> bool:
    certs = read_certs()
    return certs.get(creator_id, {}).get("status") == "verified"


# ---------------------------------------------------------------------------
# Signal 1: LLM Classifier (Groq)
# ---------------------------------------------------------------------------
LLM_PROMPT = """You are an AI content attribution classifier. Analyze the text below and assess the probability that it was generated by an AI language model (as opposed to written by a human).

Consider:
- Overly balanced or formulaic sentence structure
- Generic transitions ("furthermore", "it is important to note", "in conclusion")
- Lack of personal voice, specific anecdote, or genuine uncertainty
- Unnaturally smooth and uniform flow
- Vocabulary that is correct but feels optimized rather than chosen

Respond with ONLY a valid JSON object in this exact format (no markdown, no explanation):
{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}

Text to analyze:
"""


def classify_with_llm(text: str) -> dict:
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": LLM_PROMPT + text}],
            temperature=0,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))
        return {"score": score, "reasoning": parsed.get("reasoning", "")}
    except Exception as e:
        print(f"[LLM signal error] {e}")
        return {"score": 0.5, "reasoning": f"LLM signal unavailable: {str(e)}"}


# ---------------------------------------------------------------------------
# Signal 2: Stylometric Heuristics (pure Python)
# ---------------------------------------------------------------------------

def _split_sentences(text: str) -> list:
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    return [s for s in sentences if len(s.split()) >= 2]


def compute_stylometric_score(text: str) -> dict:
    words = text.split()
    sentences = _split_sentences(text)

    if len(sentences) < 2 or len(words) < 10:
        return {"score": 0.5, "details": {"note": "insufficient text for stylometric analysis"}}

    sent_lengths = [len(s.split()) for s in sentences]
    mean_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)
    std_dev = math.sqrt(variance)
    variance_score = max(0.0, 1.0 - (std_dev / 15.0))

    clean_words = [w.lower().strip(string.punctuation) for w in words if w.strip(string.punctuation)]
    ttr = len(set(clean_words)) / len(clean_words) if clean_words else 0.5
    ttr_distance = abs(ttr - 0.62)
    ttr_score = max(0.0, 1.0 - (ttr_distance / 0.38))

    punct_chars = sum(1 for c in text if c in string.punctuation)
    punct_density = punct_chars / len(text) if len(text) > 0 else 0
    punct_distance = abs(punct_density - 0.075)
    punct_score = max(0.0, 1.0 - (punct_distance / 0.075))

    len_distance = abs(mean_len - 21.0)
    len_score = max(0.0, 1.0 - (len_distance / 21.0))

    combined = (
        0.35 * variance_score +
        0.25 * ttr_score +
        0.20 * punct_score +
        0.20 * len_score
    )

    return {
        "score": round(max(0.0, min(1.0, combined)), 4),
        "details": {
            "sentence_count": len(sentences),
            "avg_sentence_length": round(mean_len, 2),
            "sentence_length_std_dev": round(std_dev, 2),
            "type_token_ratio": round(ttr, 4),
            "punctuation_density": round(punct_density, 4),
        }
    }


# ---------------------------------------------------------------------------
# Signal 3: Burstiness Score (pure Python)
# ---------------------------------------------------------------------------

def compute_burstiness_score(text: str) -> dict:
    stopwords = {
        "the","a","an","and","or","but","in","on","at","to","for","of","with",
        "by","from","is","are","was","were","be","been","it","this","that","i",
        "you","he","she","we","they","my","your","his","her","its","our","their",
        "not","as","so","if","do","did","have","has","had","will","would","can",
        "could","should","may","might","what","how","when","where","who","which"
    }
    tokens = [
        w.lower().strip(string.punctuation)
        for w in text.split()
        if w.lower().strip(string.punctuation) not in stopwords
        and len(w.strip(string.punctuation)) > 2
    ]

    if len(tokens) < 20:
        return {"score": 0.5, "details": {"note": "insufficient tokens for burstiness analysis"}}

    freq = Counter(tokens)
    repeated_words = [word for word, count in freq.items() if count >= 3]

    if len(repeated_words) < 2:
        return {"score": 0.5, "details": {"note": "insufficient repeated words", "vocab_size": len(freq)}}

    burstiness_values = []
    for word in repeated_words[:15]:
        positions = [i for i, t in enumerate(tokens) if t == word]
        if len(positions) < 3:
            continue
        intervals = [positions[i+1] - positions[i] for i in range(len(positions)-1)]
        mean_interval = sum(intervals) / len(intervals)
        if mean_interval == 0:
            continue
        variance = sum((x - mean_interval) ** 2 for x in intervals) / len(intervals)
        cv = math.sqrt(variance) / mean_interval
        word_burst_score = max(0.0, 1.0 - min(cv, 2.0) / 2.0)
        burstiness_values.append(word_burst_score)

    if not burstiness_values:
        return {"score": 0.5, "details": {"note": "could not compute burstiness", "vocab_size": len(freq)}}

    final_score = sum(burstiness_values) / len(burstiness_values)
    return {
        "score": round(max(0.0, min(1.0, final_score)), 4),
        "details": {
            "token_count": len(tokens),
            "vocab_size": len(freq),
            "words_analyzed": len(burstiness_values),
        }
    }


# ---------------------------------------------------------------------------
# Ensemble Confidence Scoring
# ---------------------------------------------------------------------------
LLM_WEIGHT = 0.50
STYLO_WEIGHT = 0.30
BURST_WEIGHT = 0.20


def combine_signals(llm_score: float, stylo_score: float, burst_score: float) -> float:
    combined = (
        LLM_WEIGHT * llm_score +
        STYLO_WEIGHT * stylo_score +
        BURST_WEIGHT * burst_score
    )
    return round(max(0.0, min(1.0, combined)), 4)


def score_to_attribution(confidence: float) -> str:
    if confidence >= 0.70:
        return "likely_ai"
    elif confidence >= 0.40:
        return "uncertain"
    else:
        return "likely_human"


# ---------------------------------------------------------------------------
# Transparency Label
# ---------------------------------------------------------------------------
def generate_label(confidence: float, certificate: bool = False) -> str:
    if certificate:
        return (
            "This content was created by a Verified Human creator. "
            "The creator has completed an additional verification step confirming human authorship."
        )
    if confidence >= 0.70:
        return (
            "Our system's analysis suggests this content was likely AI-generated. "
            "This label is based on automated analysis and may not be accurate. "
            "If you are the creator and believe this is wrong, you can submit an appeal."
        )
    elif confidence >= 0.40:
        return (
            "Our system could not confidently determine whether this content was written by a "
            "human or generated by AI. The analysis is inconclusive. If you are the creator, "
            "you may submit an appeal to provide additional context."
        )
    else:
        return (
            "Our system's analysis suggests this content was likely written by a human. "
            "Attribution labels help readers understand the origin of creative work."
        )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

def _string_field(data: dict, name: str) -> str:
    value = data.get(name)
    return value.strip() if isinstance(value, str) else ""


def _admin_required(view):
    @wraps(view)
    def protected(*args, **kwargs):
        admin_key = os.environ.get("ADMIN_API_KEY")
        if not admin_key:
            return jsonify({"error": "Admin access is not configured"}), 503

        supplied_key = request.headers.get("X-Admin-Key", "")
        if not secrets.compare_digest(supplied_key, admin_key):
            return jsonify({"error": "Unauthorized"}), 401
        return view(*args, **kwargs)

    return protected


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = _string_field(data, "text")
    creator_id = _string_field(data, "creator_id")

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    word_count = len(text.split())
    short_text_warning = word_count < 50
    verified = is_verified(creator_id)

    # Run all three signals
    llm_result = classify_with_llm(text)
    llm_score = llm_result["score"]

    stylo_result = compute_stylometric_score(text)
    stylo_score = stylo_result["score"]

    burst_result = compute_burstiness_score(text)
    burst_score = burst_result["score"]

    # Ensemble confidence
    confidence = combine_signals(llm_score, stylo_score, burst_score)

    # Short text: cap at uncertain to avoid confident mislabeling
    if short_text_warning and confidence >= 0.70:
        confidence = 0.69

    attribution = score_to_attribution(confidence)
    label = generate_label(confidence, certificate=verified)

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    log_entry = {
        "entry_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "stylometric_score": round(stylo_score, 4),
        "burstiness_score": round(burst_score, 4),
        "status": "classified",
        "short_text_warning": short_text_warning,
        "verified_creator": verified,
    }
    append_log(log_entry)

    store_content(content_id, {
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "status": "classified",
        "timestamp": timestamp,
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "signal_scores": {
            "llm": round(llm_score, 4),
            "stylometric": round(stylo_score, 4),
            "burstiness": round(burst_score, 4),
        },
        "label": label,
        "verified_creator": verified,
        "short_text_warning": short_text_warning,
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = _string_field(data, "content_id")
    creator_reasoning = _string_field(data, "creator_reasoning")

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    content = get_content(content_id)
    if not content:
        return jsonify({"error": f"No content found with id: {content_id}"}), 404

    update_content_status(content_id, "under_review")

    appeal_entry = {
        "entry_type": "appeal",
        "content_id": content_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "creator_reasoning": creator_reasoning,
        "original_attribution": content["attribution"],
        "original_confidence": content["confidence"],
        "status": "under_review",
    }
    append_log(appeal_entry)

    return jsonify({
        "message": "Appeal received and logged. Your content has been marked for human review.",
        "content_id": content_id,
        "status": "under_review",
    }), 200


@app.route("/verify", methods=["POST"])
def verify():
    """Creator submits a verification request to earn a Verified Human certificate."""
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    creator_id = _string_field(data, "creator_id")
    statement = _string_field(data, "statement")

    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400
    if not statement:
        return jsonify({"error": "Missing required field: statement"}), 400

    certs = read_certs()
    if certs.get(creator_id, {}).get("status") == "verified":
        return jsonify({
            "message": "Creator is already verified.",
            "creator_id": creator_id,
            "status": "verified",
        }), 200

    certs[creator_id] = {
        "creator_id": creator_id,
        "statement": statement,
        "status": "pending",
        "submitted_at": datetime.now(timezone.utc).isoformat(),
    }
    write_certs(certs)

    return jsonify({
        "message": "Verification request submitted. Awaiting admin approval.",
        "creator_id": creator_id,
        "status": "pending",
    }), 200


@app.route("/admin/approve_certificate", methods=["POST"])
@_admin_required
def approve_certificate():
    """Admin endpoint to approve a pending verification request."""
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    creator_id = _string_field(data, "creator_id")
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    certs = read_certs()
    if creator_id not in certs:
        return jsonify({"error": f"No verification request found for creator_id: {creator_id}"}), 404

    certs[creator_id]["status"] = "verified"
    certs[creator_id]["verified_at"] = datetime.now(timezone.utc).isoformat()
    write_certs(certs)

    append_log({
        "entry_type": "certificate_issued",
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": "verified",
    })

    return jsonify({
        "message": f"Certificate approved. {creator_id} is now a Verified Human creator.",
        "creator_id": creator_id,
        "status": "verified",
    }), 200


@app.route("/log", methods=["GET"])
@_admin_required
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-50:], "total": len(entries)}), 200


@app.route("/dashboard", methods=["GET"])
@_admin_required
def dashboard():
    entries = read_log()
    submissions = [e for e in entries if e.get("entry_type") == "submission"]
    appeals = [e for e in entries if e.get("entry_type") == "appeal"]
    total = len(submissions)

    if total == 0:
        return jsonify({"message": "No submissions yet"}), 200

    verdict_distribution = {
        "likely_ai": sum(1 for e in submissions if e.get("attribution") == "likely_ai"),
        "uncertain": sum(1 for e in submissions if e.get("attribution") == "uncertain"),
        "likely_human": sum(1 for e in submissions if e.get("attribution") == "likely_human"),
    }

    appeal_rate = round(len(appeals) / total, 4)
    avg_confidence = round(sum(e.get("confidence", 0) for e in submissions) / total, 4)

    agreement_count = 0
    for e in submissions:
        llm = e.get("llm_score", 0.5)
        sty = e.get("stylometric_score", 0.5)
        bur = e.get("burstiness_score", 0.5)
        if llm is not None and sty is not None and bur is not None:
            if (llm >= 0.5 and sty >= 0.5 and bur >= 0.5) or (llm < 0.5 and sty < 0.5 and bur < 0.5):
                agreement_count += 1
    signal_agreement_rate = round(agreement_count / total, 4)

    return jsonify({
        "total_submissions": total,
        "total_appeals": len(appeals),
        "verdict_distribution": verdict_distribution,
        "appeal_rate": appeal_rate,
        "avg_confidence": avg_confidence,
        "signal_agreement_rate": signal_agreement_rate,
    }), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"}), 200


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    app.run(port=5001)
